server:
  port: 8888

#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


kira:
  security:
    login-success-url: /loginsuccess.html
    login-failure-url: /loginfail.html